stages:
  - test
  - release_dev
  - deploy_dev

variables:
  CONTAINER_REGISTRY: eastus2tgacr.azurecr.io
  SERVICE_NAME: auth-api
  SERVICE_NAMESPACE: 'tg'
  LOCATION: 'eastus2'
  SERVICE_ROUTE_PREFIX: 'auth'

image: docker:18.09.7
services:
  - docker:18.09.7-dind

'Test code':
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
      - dotnet build ./src
  only:
    - merge_requests

.release:
  image: docker:18.09.7
  services:
    - docker:18.09.7-dind
  script:
      - cd src
      - docker login $CONTAINER_REGISTRY -u $SERVICE_USER -p $SERVICE_USER_PWD
      - docker build -t $CONTAINER_REGISTRY/$SERVICE_NAME:$ENV-$CI_PIPELINE_IID .
      - docker push $CONTAINER_REGISTRY/$SERVICE_NAME:$ENVIRONMENT-$CI_PIPELINE_IID

'DEV Publish docker image':
  stage: release_dev
  extends: .release
  variables:
    ENVIRONMENT: dev
  only:
    - master

.deploy:
  before_script:
      - sed -i -e 's/##SERVICE_NAME##/$SERVICE_NAME/g' k8s/autoscale.yaml
      - sed -i -e 's/##ENVIRONMENT##/$ENVIRONMENT/g' k8s/autoscale.yaml
      - sed -i -e 's/##SERVICE_NAMESPACE##/$SERVICE_NAMESPACE/g' k8s/autoscale.yaml
      - sed -i -e 's/##MIN_REPLICAS##/$MIN_REPLICAS/g' k8s/autoscale.yaml
      - sed -i -e 's/##MAX_REPLICAS##/$MAX_REPLICAS/g' k8s/autoscale.yaml
      - sed -i -e 's/##CPU_SCALE_THRESHOLD##/$CPU_SCALE_THRESHOLD/g' k8s/autoscale.yaml
      - sed -i -e 's/##MEMORY_SCALE_THRESHOLD##/$MEMORY_SCALE_THRESHOLD/g' k8s/autoscale.yaml

      - sed -i -e 's/##SERVICE_NAMESPACE##/$SERVICE_NAMESPACE/g' k8s/namespace.yaml
      - sed -i -e 's/##ENVIRONMENT##/$ENVIRONMENT/g' k8s/namespace.yaml

      - sed -i -e 's/##SERVICE_NAME##/$SERVICE_NAME/g' k8s/deployment.yaml
      - sed -i -e 's/##LOCATION##/$LOCATION/g' k8s/deployment.yaml
      - sed -i -e 's/##INSTANCE_REPLICAS##/$INSTANCE_REPLICAS/g' k8s/deployment.yaml
      - sed -i -e 's/##CONTAINER_REGISTRY##/$CONTAINER_REGISTRY/g' k8s/deployment.yaml
      - sed -i -e 's/##IMAGE_TAG##/$ENVIRONMENT-$CI_PIPELINE_IID/g' k8s/deployment.yaml
      - sed -i -e 's/##ASPNETCORE_ENVIRONMENT##/$ASPNETCORE_ENVIRONMENT/g' k8s/deployment.yaml
      - sed -i -e 's/##SERVICE_NAMESPACE##/$SERVICE_NAMESPACE/g' k8s/deployment.yaml
      - sed -i -e 's/##ENVIRONMENT##/$ENVIRONMENT/g' k8s/deployment.yaml
      - sed -i -e 's/##MEMORY_REQUEST##/$MEMORY_REQUEST/g' k8s/deployment.yaml
      - sed -i -e 's/##CPU_REQUEST##/$CPU_REQUEST/g' k8s/deployment.yaml
      - sed -i -e 's/##MEMORY_LIMIT##/$MEMORY_LIMIT/g' k8s/deployment.yaml
      - sed -i -e 's/##CPU_LIMIT##/$CPU_LIMIT/g' k8s/deployment.yaml
      
      - sed -i -e 's/##SERVICE_NAME##/$SERVICE_NAME/g' k8s/service.yaml
      - sed -i -e 's/##SERVICE_NAMESPACE##/$SERVICE_NAMESPACE/g' k8s/service.yaml
      - sed -i -e 's/##ENVIRONMENT##/$ENVIRONMENT/g' k8s/service.yaml

      - sed -i -e 's/##SERVICE_NAME##/$SERVICE_NAME/g' k8s/ingress_route.yaml
      - sed -i -e 's/##SERVICE_NAMESPACE##/$SERVICE_NAMESPACE/g' k8s/ingress_route.yaml
      - sed -i -e 's/##ENVIRONMENT##/$ENVIRONMENT/g' k8s/ingress_route.yaml
      - sed -i -e 's/##SERVICE_ROUTE_PREFIX##/$SERVICE_ROUTE_PREFIX/g' k8s/ingress_route.yaml

  script:
    - echo 'TODO DEPLOY'    

'DEV Deploy to cluster':
  stage: deploy_dev
  extends: .deploy
  variables:
    ENVIRONMENT: dev
    ASPNETCORE_ENVIRONMENT: 'Development'
    MIN_REPLICAS: 1
    MAX_REPLICAS: 2
    CPU_REQUEST: '100m'
    CPU_LIMIT: '300m'
    CPU_SCALE_THRESHOLD: '225m'
    MEMORY_REQUEST: '350M'
    MEMORY_LIMIT: '500M'
    MEMORY_SCALE_THRESHOLD: '425M'
  only:
    - master
      
