# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
variables:
  ### REPO STRUCTURE-SPECIFIC VARIABLES ###
  deploymentConfigsFolder: '$(Build.SourcesDirectory)/deployment'
  srcFolder: '$(Build.SourcesDirectory)/src'
  ### PIPELINE-SPECIFIC VARIABLES ###
  vmImageName: 'ubuntu-latest'
  dockerImageTag: '$(Build.SourceVersion)'
  ### ENVIRONMENT-SPECIFIC VARIABLES ###
  serviceNamespace: 'flow'
  location: 'eastus'
  dockerRegistryServiceConnection: 'asg-acr-dev-flow'
  containerRegistry: 'eastusflowacr.azurecr.io'
  environment: 'dev'
  resourceGroup: 'ASG.Development.Flow'
  azureSubscriptionEndpoint: 'asg-dev-flow'
  ### SERVICE-SPECIFIC VARIABLES ###
  dockerfilePath: '$(srcFolder)/Surf.Job.Api/Dockerfile'
  # serviceName is used as Docker image name as well
  serviceName: 'jobs-api'
  serviceRoutePrefix: 'jobs'
  aspnetcoreEnvironment: 'Development'
  minReplicas: 1
  maxReplicas: 2
  cpuRequest: '100m'
  cpuLimit: '300m'
  cpuScaleThreshold: '225m'
  memoryRequest: '350M'
  memoryLimit: '500M'
  memoryScaleThreshold: '425M'

pipelines:
  default:
    - step:
        name: Buld and Test
        image: mcr.microsoft.com/dotnet/sdk:5.0
        script:
            - dotnet build ./src
        services:
          - docker