pipelines:
  default:
    - step:
        name: Buld and Test
        image: mcr.microsoft.com/dotnet/sdk:5.0
        script:
            - dotnet build ./src

  branches:
    master:          
      - step:
          name: Deploy to Dev
          deployment: dev
          script:
            - sed -i -e 's/##SERVICE_NAME##/$serviceName/g' k8s/autoscale.yaml
            - dotnet publish -c Release
